### ISSUE TITLE
Met verwijder marker worden alle markers verwijderd

### ISSUE THREAD

**Issue by milovanderlinden** [dogodigi/pdokkaart#24]
Wanneer je 2 markers maakt en dan 1 marker wil verwijderen met “verwijderen marker”, verdwijnt alles en schiet de kaart terug in de uitgezoomde stand.

![image001](https://cloud.githubusercontent.com/assets/106038/4378965/aff02398-435c-11e4-8bf8-66e7df551ed3.png)

**Comment by rduivenvoorde** [comment]
als deze gefixed, @milovanderlinden kun jij deze dan sluiten?

**Comment by milovanderlinden** [comment]
Ik zou graag willen dat het even gecontroleerd wordt in de nieuwe oplevering. Zie het als een kleine "regressie-test"

**Comment by raymondnijssen** [comment]
Probleem kan niet worden gereproduceerd, dus zal nu goed zijn.
