### ISSUE TITLE
Dezelfde kaartlaag kan meerdere malen worden toegevoegd 

### ISSUE THREAD

**Issue by raymondnijssen** [dogodigi/pdokkaart#37]
Aan/uitzetten functies met checkboxes in Wizard:
Zelfde kaartlaag is meerdere malen toe te voegen (standaard PDOK Kaart functionaliteit)

(0006a / 1001-009)

**Comment by rduivenvoorde** [comment]
Er zijn twee manieren om WMS lagen toe te voegend:

- via de dropdown (wordt dan toegevoegd op basis van de 'naam/key' uit de defaultlayers config file)
- via een url/layernames/typefeatureinfo

In het eerste geval is het toevoegen van dezelfde naam niet zinnig waarschijnlijk, maar ALLE lagen zijn eenvoudig te verwijderen, en dan kan de laag daarna nogmaals 1x worden toegevoegd.

In het geval van het toevoegen van een url (via de wizard) is het de bedoeling dat er echt maar 1 wms-service wordt toegevoegd. Het toevoegend via die url (in de wizard) zorgt namelijk voor 'het vullen' van de query parameter:
- wmsurl
- wmslayers
- wmsinfoformat
en die kunnen op dit moment ook niet omgaan met meerdere 'values' per key: je kunt dus niet twee verschillende wms-url's opgeven.
Dit ZOU geimplementeerd kunnen worden (bv door pipe-separated ('|') te gaan gebruiken, maar anderzijds beschouw ik zoiets als iets wat slimmer even via code kan worden gedaan na het aanmaken van een simpele app.

implementatievoorstel nu: ALS er al een wms of wmts layer is toegevoegd via de url/layers/infoformat inputs, dan bij een volgende keer een 'confirm'-alert tonen die de gebruiker vraagt of de huidige wel of niet moet worden overSCHREVEN.

**Comment by milovanderlinden** [comment]
Prima oplossing.
