### ISSUE TITLE
WMS titel niet zichtbaar

### ISSUE THREAD

**Issue by raymondnijssen** [dogodigi/pdokkaart#39]
Wanneer een niet-pdok WMS wordt toegevoegd krijgt deze de titel "WMS layer" in de layerSwitcher. Geldt waarschijnlijk ook voor WFS en WMTS layers.

(0015a)

**Comment by rduivenvoorde** [comment]
WMS gefixed, api toont nu de 'layernames' van de WMS:

https://github.com/raymondnijssen/pdokkaart/commit/fdb2e98e4fb74d02760e39277dc2db4dc532183e

WFS interface zoals 'addWMSlayer' is er niet.

WMTS is al goed.
